baseurl = "/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
title = "Magical trees, take me home."
theme = "diary"
enableGitInfo = true

#Google Analytics
[services]
  [services.googleAnalytics]
    id = "G-KKMPD9QE50"  # Your Google Analytics ID

# paginate = 7

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[markup.goldmark.renderer]
  unsafe = true

[params]
subtitle = "SnowMemo's blog"
favicon = "/img/favicon/favicon.ico"
enableGiscus = true
enableReadingTime=true
enableAutoDarkMode=true

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "SnowMemo" # will set 'og:site_name'
description = "Markdown around"  # will set 'og:description'

[params.gitalk]
  owner = "snowmemo"
  repo = "snowmemo.github.io"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="snowmemo.github.io"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

[params.giscus]
    data_repo="snowmemo/snowmemo.github.io"
    data_repo_id="R_kgDOGXgP8g"    
    data_category="Announcements"
    data_category_id="DIC_kwDOGXgP8s4CiMOo"
    data_mapping="title"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="zh-CN"
    crossorigin="anonymous"

[[menu.main]]
url = "/posts"
name = "归档"
weight = 1
[[menu.main]]
url = "/now"
name = "Now"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/categories"
name = "分类"
weight = 4
[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 5

